# -*- coding: utf-8 -*-
"""NumberGuessingGame.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TJsv3_pGwBfZrz2sP_sDKS58TQIMyOUt

NUMBER GUESSING GAME

You will have to guess the right number within the 5 chances given in order to win the game.
"""

import random
import time
a = random.randrange(1,100)
print("Welcome to the guessing game\n You will be given 5 chances.\nAll the best!")
time.sleep(2)
c=4
i = int(input("Guess a number in range 1-100 : "))
while a!=i and c>0 : 
  if i < a  :
    print("Too low")   
    print( "{} attempts left".format(c))
    c-=1
    i = int(input("Guess again : "))
  elif i > a : 
      print("Too high")
      print( "{} attempts left".format(c))
      c-=1
      i = int(input("Guess again : "))
  else  :        
       break 
if c>0 :       
 print("You guessed the number!!")        
else :
 print("You ran out of chances\nNumber was {}".format(a))